from tabular_shenanigans._model_builders import validate_model_parameter_overrides
from tabular_shenanigans._model_registry import (
    DEFAULT_MODEL_ID_BY_TASK,
    MODEL_REGISTRY,
    build_model,
    build_model_fit_kwargs,
    build_tuning_space,
    get_default_model_id,
    get_model_definition,
    get_supported_model_ids,
    get_task_model_registry,
    get_tunable_model_ids,
    is_model_id_valid_for_task,
    is_model_tunable,
    iter_model_gpu_routing_entries,
    resolve_candidate_model_id,
    resolve_model_id,
    resolve_model_matrix_output_kind,
    validate_model_preprocessing_compatibility,
)
from tabular_shenanigans._model_types import (
    BinaryLabelEncodingClassifier,
    GpuRoutingRule,
    ModelDefinition,
    SingleTargetRegressionAdapter,
)

__all__ = [
    "BinaryLabelEncodingClassifier",
    "DEFAULT_MODEL_ID_BY_TASK",
    "GpuRoutingRule",
    "MODEL_REGISTRY",
    "ModelDefinition",
    "SingleTargetRegressionAdapter",
    "build_model",
    "build_model_fit_kwargs",
    "build_tuning_space",
    "get_default_model_id",
    "get_model_definition",
    "get_supported_model_ids",
    "get_task_model_registry",
    "get_tunable_model_ids",
    "is_model_id_valid_for_task",
    "is_model_tunable",
    "iter_model_gpu_routing_entries",
    "resolve_candidate_model_id",
    "resolve_model_id",
    "resolve_model_matrix_output_kind",
    "validate_model_parameter_overrides",
    "validate_model_preprocessing_compatibility",
]
